<a href="https://colab.research.google.com/github/Suyash088/ml_lab/blob/main/ML_prac7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aim : to apply suport vector machine for classification and analyze the impact of different kernelson model accuracy

Suyash Meshram CS23138

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path ="/content/drive/MyDrive/Ml_data_set/pulsar_stars - pulsar_stars.csv"
df=pd.read_csv(path)
df.head(5)

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0

In [ ]:
df.shape

(17898, 9)

In [ ]:
df.columns

Index(['Mean of the integrated profile',
       'Standard deviation of the integrated profile',
       'Excess kurtosis of the integrated profile',
       'Skewness of the integrated profile', 'Mean of the DM-SNR curve',
       'Standard deviation of the DM-SNR curve',
       'Excess kurtosis of the DM-SNR curve', 'Skewness of the DM-SNR curve',
       'target_class'],
      dtype='object')

In [ ]:
df.isnull().any().any()

np.False_

In [ ]:
X = df.drop(columns=['target_class'])
y = df['target_class']

In [ ]:
X.head()

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306

In [ ]:
new_column_names = {
    'Mean of the integrated profile': 'mean_ip',
    'Standard deviation of the integrated profile': 'std_ip',
    'Excess kurtosis of the integrated profile': 'kurt_ip',
    'Skewness of the integrated profile': 'skew_ip',
    'Mean of the DM-SNR curve': 'mean_dm_snr',
    'Standard deviation of the DM-SNR curve': 'std_dm_snr',
    'Excess kurtosis of the DM-SNR curve': 'kurt_dm_snr',
    'Skewness of the DM-SNR curve': 'skew_dm_snr',
    'target_class': 'target_class'
}
df = df.rename(columns=new_column_names)
print("New column names:")
print(df.columns)

New column names:
Index(['mean_ip', 'std_ip', 'kurt_ip', 'skew_ip', 'mean_dm_snr', 'std_dm_snr',
       'kurt_dm_snr', 'skew_dm_snr', 'target_class'],
      dtype='object')

In [ ]:
X = pd.get_dummies(X,dtype = int)

In [ ]:
X.head()

    skew_ip  mean_dm_snr  std_dm_snr  kurt_dm_snr  skew_dm_snr
0 -0.699648     3.199833   19.110426     7.975532    74.242225
1 -0.515088     1.677258   14.860146    10.576487   127.393580
2  1.051164     3.121237   21.744669     7.735822    63.171909
3 -0.636238     3.642977   20.959280     6.896499    53.593661
4  1.123492     1.178930   11.468720    14.269573   252.567306

In [ ]:
X = df.iloc[:,3:-1]
X = pd.get_dummies(X, dtype=int)
X

        skew_ip  mean_dm_snr  std_dm_snr  kurt_dm_snr  skew_dm_snr
0     -0.699648     3.199833   19.110426     7.975532    74.242225
1     -0.515088     1.677258   14.860146    10.576487   127.393580
2      1.051164     3.121237   21.744669     7.735822    63.171909
3     -0.636238     3.642977   20.959280     6.896499    53.593661
4      1.123492     1.178930   11.468720    14.269573   252.567306
...         ...          ...         ...          ...          ...
17893 -0.738123     1.296823   12.166062    15.450260   285.931022
17894  0.323061    16.409699   44.626893     2.945244     8.297092
17895 -0.743025    21.430602   58.872000     2.499517     4.595173
17896 -0.024789     1.946488   13.381731    10.007967   134.238910
17897  0.089520   188.306020   64.712562    -1.597527     1.429475

[17898 rows x 5 columns]

In [ ]:
y=df.iloc[:,-1]
print(y)

0        0
1        0
2        0
3        0
4        0
        ..
17893    0
17894    0
17895    0
17896    0
17897    0
Name: target_class, Length: 17898, dtype: int64

In [ ]:
X.shape

(17898, 5)

In [ ]:
X.columns

Index(['skew_ip', 'mean_dm_snr', 'std_dm_snr', 'kurt_dm_snr', 'skew_dm_snr'], dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,test_size=0.3,random_state=42)
X_train.shape,X_test.shape

((12528, 5), (5370, 5))

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[-0.2885854 , -0.32101331, -0.40338108, -0.19481754, -0.37780071],
       [ 0.25938061, -0.34699026, -0.44578706,  0.23837256, -0.02857034],
       [-0.33434359, -0.33538534, -0.2004973 ,  0.038556  , -0.29531727],
       ...,
       [-0.21670413, -0.40151363, -0.75001383,  1.92294752,  1.91898259],
       [-0.32298516, -0.29769052, -0.24457614, -0.20616758, -0.4040674 ],
       [-0.25669812, -0.40205011, -0.74159513,  2.05677923,  2.08022728]])

In [ ]:
y_train

12223    0
1919     0
2753     0
17220    0
12110    0
        ..
11284    0
11964    0
5390     0
860      0
15795    0
Name: target_class, Length: 12528, dtype: int64

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svc = SVC()
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.9737430167597766

In [ ]:
print('Confusion Matrix')
cm=confusion_matrix(y_pred,y_test)
print(confusion_matrix(y_pred,y_test))

Confusion Matrix
[[4864  121]
 [  20  365]]

In [ ]:
svc =SVC(C= 100.0)
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.9743016759776536

In [ ]:
svc =SVC(C= 1000.0)
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.9750465549348231

In [ ]:
linear_svc = SVC(kernel='linear',C=1.0)
linear_svc.fit(X_train, y_train)
y_pred = linear_svc.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.9711359404096834

In [ ]:
linear_svc = SVC(kernel='linear',C=100.0)
linear_svc.fit(X_train, y_train)
y_pred = linear_svc.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.9715083798882681

In [ ]:
linear_svc = SVC(kernel='linear',C=1000.0)
linear_svc.fit(X_train, y_train)
y_pred = linear_svc.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.9716945996275606

In [ ]:
poly_svc = SVC(kernel='poly',C=1.0)
poly_svc.fit(X_train, y_train)
y_pred = linear_svc.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.9716945996275606

In [ ]:
poly_svc = SVC(kernel='poly',C=100.0)
poly_svc.fit(X_train, y_train)
y_pred = linear_svc.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.9716945996275606

In [ ]:
poly_svc = SVC(kernel='poly',C=1000.0)
poly_svc.fit(X_train, y_train)
y_pred = linear_svc.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.9716945996275606

In [ ]:
sigmoid_svc = SVC(kernel='sigmoid',C=1.0)
sigmoid_svc.fit(X_train, y_train)
y_pred = linear_svc.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.9716945996275606

In [ ]:
sigmoid_svc = SVC(kernel='sigmoid',C=100.0)
sigmoid_svc.fit(X_train, y_train)
y_pred = linear_svc.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.9716945996275606

In [ ]:
sigmoid_svc = SVC(kernel='sigmoid',C=1000.0)
sigmoid_svc.fit(X_train, y_train)
y_pred = linear_svc.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.9716945996275606